import Head from "next/head";
import { IChildrenProps } from "../interface/children-props.interface";

export interface IPageWrapper extends IChildrenProps {
  title?: string;
}

const PageWrapper: React.FC<IPageWrapper> = ({ title, children }) => {
  return (
    <>
      <Head>
        <title>{`${title}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./dtfest_logo.png" />
      </Head>
      <main>{children}</main>
    </>
  );
};

export default PageWrapper;
